language: python
python:
- '2.7'
- '3.4'
- '3.5'
before_install:
- |
  wget \
    http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh \
    -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b -p $(pwd)/miniconda"
- export PATH=$(pwd)/miniconda/bin:$PATH
- conda update --yes conda
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- |
  conda create \
    --yes -q -n pyenv \
    python=$TRAVIS_PYTHON_VERSION \
    numpy scipy sympy matplotlib seaborn nose
- source activate pyenv
- pip install .
script: nosetests ./symfit/tests/tests.py
deploy:
  # test pypi
  - provider: pypi
    distributions: sdist
    server: https://testpypi.python.org/pypi
    user: "tbuli"
    password:
    on:
      branch: deploy
      tags: false
      condition: $TRAVIS_PYTHON_VERSION = "2.7"
  # production pypi
  - provider: pypi
    distributions: sdist
    user: "tbuli"
    password:
      secure:
    on:
      branch: master
      tags: true
      condition: $TRAVIS_PYTHON_VERSION = "2.7"