language: python
# Choose the supported versions of python.
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
cache:
  - pip
before_install:
## Provide a X display for plotting
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
## Install the dependencies
install:
  # Upgrade pip to enable the --only-binary flag
  - pip install --upgrade pip
  - pip install --upgrade --only-binary numpy,scipy --requirement requirements.txt
  - pip install --upgrade nose
  - pip install --upgrade --only-binary matplotlib matplotlib seaborn
  - pip install .
# Run tests
script: nosetests ./symfit/tests/tests.py
